### ISSUE TITLE
Unable to communicate to satan. Not sure whats happening

### ISSUE THREAD

**Issue by pocha** [vperron/satan#1]
Hi, I am able to successfully build & install satan on my Openwrt box. 

I config file, I have specified the commands & answer endpoint as my linux machine (both in same domain - just a test setup). I have kept the default ports. 

Now when I run command python script from my server, I do not get any print in minion_stdout (I have it running before I run command script). I dont think there is any communication. There are no logs/debug message satan is generating for me to able to figure things out.

**Comment by vperron** [comment]
Well I guess there's an issue with the way your ZeroMQ connection is established (or not).

I suggest you try and debug it using prints / gdb / whatever, I don't support this since 3 years :)

**Comment by pocha** [comment]
While, I am on it, quickly wanted to check with you - if there needs to be some kind of ZeroMQ server that keeps persistent connection with clients.

This is my current setup 
1. Satan is hearing for commands on `http://192.168.7.141:10080` . It is sending answers on `http://192.168.7.141:10081`. 
2. I have `minion_stdout` running for any output on `http://*:10081`. This is running on the linux machine with ip `192.168.7.141`
3. I fire up `control` from linux machine which sends a command on `http://*:10080`. The command is sent & the program exits.

Can you tell me if this looks good setup-wise ? Also, I do not see any zeromq server being setup anywhere. The `control` scripts comes up, sends command on port 10080 & goes away. Does `satan` suppose to catch that message ?

**Comment by pocha** [comment]
I figured what was the issue. The `zsocket_poll(...)` call had timeout as 0. I made it to 100 (msec) & it started to work fine. 

I think the code is using older version of zeromq library which is deprecated now. But I guess I would stick with it for time being.
